spring.datasourse.url=jdbc:h2:mem:personsdb
spring.datasourse.driver-class-mane=org.h2.Driver
spring.datasourse.username=sa
spring.datasourse.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true